import type { Locale } from "@/i18n/messages";

const copy = {
  "zh-CN": {
    stepsLabel: "注册进度",
    stepDetails: "填写信息",
    stepEmail: "验证邮箱",
    stepLogin: "登录使用",
    registerEyebrow: "学校邮箱验证",
    registerHelper: "验证链接 30 分钟内有效",
    registerTitle: "创建教师账号",
    registerDescription: "填写账号信息。我们会向学校邮箱发送一次性验证链接，验证后才创建账号。",
    usernameLabel: "用户名",
    usernamePlaceholder: "至少 3 个字符",
    emailLabel: "学校邮箱",
    emailPlaceholder: "name@university.edu.cn",
    emailHint: "请使用你可以立即查收邮件的学校邮箱。",
    passwordLabel: "设置密码",
    passwordPlaceholder: "至少 8 个字符",
    confirmationLabel: "确认密码",
    confirmationPlaceholder: "再次输入密码",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    showConfirmation: "显示确认密码",
    hideConfirmation: "隐藏确认密码",
    sendLink: "发送验证链接",
    sendingLink: "正在发送…",
    alreadyRegistered: "已有账号？",
    backToLogin: "返回登录",
    usernameTooShort: "用户名至少需要 3 个字符。",
    invalidEmail: "请输入有效的学校邮箱地址。",
    passwordTooShort: "密码至少需要 8 个字符。",
    passwordTooLong: "密码不能超过 128 个字符。",
    passwordsMismatch: "两次输入的密码不一致。",
    requestNetworkError: "暂时无法连接注册服务，请检查网络后重试。",
    requestInvalid: "请检查用户名、学校邮箱和密码后再试。",
    requestRateLimited: "发送次数较多，请在 {time} 后再试。",
    requestUnavailable: "暂时无法发送验证邮件，请稍后重试。",
    requestGenericError: "验证邮件未发送，请稍后重试。",
    checkEyebrow: "验证邮件已发送",
    checkHelper: "链接 30 分钟内有效",
    checkTitle: "请查收学校邮箱",
    checkDescription: "如果该邮箱可以注册，验证邮件已发送至 {email}。",
    checkPrivacy: "为保护账号信息，无论邮箱是否已注册，这里都会显示相同结果。",
    checkStepInbox: "打开收件箱，找到 SmarTAI 验证邮件。",
    checkStepSpam: "没有看到时，请检查垃圾邮件或稍等片刻。",
    checkStepLink: "点击邮件中的链接，再确认创建账号。",
    expiresIn: "本次链接将在 {time} 后失效",
    linkExpired: "本次链接已到期，可以重新发送新链接。",
    resendIn: "{time} 后可重新发送",
    resendLink: "重新发送",
    resendingLink: "正在重新发送…",
    resentTitle: "新链接已发送",
    resentDescription: "旧链接已失效，请使用最新邮件中的链接。",
    changeDetails: "返回修改信息",
    missingFlowTitle: "注册信息已失效",
    missingFlowDescription: "请重新填写注册信息，我们会发送一封新的验证邮件。",
    restartRegistration: "重新填写",
    verifyEyebrow: "确认学校邮箱",
    verifyHelper: "一次性安全链接",
    verifyTitle: "完成邮箱验证",
    verifyDescription: "确认后才会创建教师账号。该链接只能成功使用一次。",
    verifySecurityNote: "验证完成后仍需使用用户名和密码登录，不会自动进入工作台。",
    confirmRegistration: "确认并创建账号",
    confirmingRegistration: "正在确认…",
    verifyNetworkError: "暂时无法验证链接，请保持此页面打开并重试。",
    verifyRetry: "重试验证",
    successEyebrow: "邮箱验证完成",
    successHelper: "账号已安全创建",
    successTitle: "注册完成",
    successDescription: "教师账号已创建。现在可以使用用户名和密码登录。",
    goToLogin: "前往登录",
    expiredEyebrow: "链接已过期",
    expiredHelper: "30 分钟有效期已结束",
    expiredTitle: "需要新的验证链接",
    expiredDescription: "为保护账号安全，本次链接已失效。请重新填写注册信息或返回原页面重新发送。",
    usedEyebrow: "链接已使用",
    usedHelper: "一次性链接不能重复使用",
    usedTitle: "该验证已经完成",
    usedDescription: "如果你已经完成注册，请直接登录；否则重新开始注册。",
    invalidEyebrow: "链接不可用",
    invalidHelper: "链接缺失或已损坏",
    invalidTitle: "无法验证此链接",
    invalidDescription: "请确认链接复制完整，或重新填写注册信息获取新邮件。",
    backToEmailPage: "返回邮件页面",
  },
  "en-US": {
    stepsLabel: "Registration progress",
    stepDetails: "Account details",
    stepEmail: "Verify email",
    stepLogin: "Sign in",
    registerEyebrow: "School email verification",
    registerHelper: "Link valid for 30 minutes",
    registerTitle: "Create teacher account",
    registerDescription: "Enter your account details. We will send a one-time link to your school email and create the account only after verification.",
    usernameLabel: "Username",
    usernamePlaceholder: "At least 3 characters",
    emailLabel: "School email",
    emailPlaceholder: "name@university.edu",
    emailHint: "Use a school inbox you can access now.",
    passwordLabel: "Password",
    passwordPlaceholder: "At least 8 characters",
    confirmationLabel: "Confirm password",
    confirmationPlaceholder: "Enter password again",
    showPassword: "Show password",
    hidePassword: "Hide password",
    showConfirmation: "Show confirmation password",
    hideConfirmation: "Hide confirmation password",
    sendLink: "Send verification link",
    sendingLink: "Sending…",
    alreadyRegistered: "Already have an account?",
    backToLogin: "Back to sign in",
    usernameTooShort: "Username must contain at least 3 characters.",
    invalidEmail: "Enter a valid school email address.",
    passwordTooShort: "Password must contain at least 8 characters.",
    passwordTooLong: "Password cannot exceed 128 characters.",
    passwordsMismatch: "The passwords do not match.",
    requestNetworkError: "Unable to reach registration. Check your connection and try again.",
    requestInvalid: "Check the username, school email, and password, then try again.",
    requestRateLimited: "Too many requests. Try again in {time}.",
    requestUnavailable: "We cannot send a verification email right now. Try again shortly.",
    requestGenericError: "The verification email was not sent. Try again shortly.",
    checkEyebrow: "Verification email sent",
    checkHelper: "Link valid for 30 minutes",
    checkTitle: "Check your school email",
    checkDescription: "If this email can be registered, a verification message was sent to {email}.",
    checkPrivacy: "To protect account information, this page shows the same result whether or not an account already exists.",
    checkStepInbox: "Open your inbox and find the SmarTAI verification email.",
    checkStepSpam: "If it is not there, check spam or wait a moment.",
    checkStepLink: "Open the link in the email, then confirm account creation.",
    expiresIn: "This link expires in {time}",
    linkExpired: "This link has expired. You can send a new one.",
    resendIn: "Resend available in {time}",
    resendLink: "Resend link",
    resendingLink: "Resending…",
    resentTitle: "New link sent",
    resentDescription: "The previous link is no longer valid. Use the latest email.",
    changeDetails: "Change account details",
    missingFlowTitle: "Registration details expired",
    missingFlowDescription: "Enter your registration details again and we will send a new verification email.",
    restartRegistration: "Start again",
    verifyEyebrow: "Confirm school email",
    verifyHelper: "Single-use secure link",
    verifyTitle: "Complete email verification",
    verifyDescription: "Your teacher account is created only after confirmation. This link can succeed once.",
    verifySecurityNote: "You will still sign in with your username and password. Verification does not open the workspace automatically.",
    confirmRegistration: "Confirm and create account",
    confirmingRegistration: "Confirming…",
    verifyNetworkError: "We cannot verify the link right now. Keep this page open and try again.",
    verifyRetry: "Retry verification",
    successEyebrow: "Email verified",
    successHelper: "Account created securely",
    successTitle: "Registration complete",
    successDescription: "Your teacher account is ready. Sign in with your username and password.",
    goToLogin: "Continue to sign in",
    expiredEyebrow: "Link expired",
    expiredHelper: "The 30-minute validity period ended",
    expiredTitle: "Request a new verification link",
    expiredDescription: "For your security, this link is no longer valid. Start again or return to the email page to resend it.",
    usedEyebrow: "Link already used",
    usedHelper: "Single-use links cannot be reused",
    usedTitle: "Verification already completed",
    usedDescription: "If registration is complete, sign in. Otherwise, start registration again.",
    invalidEyebrow: "Link unavailable",
    invalidHelper: "The link is missing or damaged",
    invalidTitle: "We cannot verify this link",
    invalidDescription: "Check that the complete link was copied, or start again to receive a new email.",
    backToEmailPage: "Back to email page",
  },
} as const;

export type RegistrationCopyKey = keyof typeof copy["zh-CN"];

const placeholderPattern = /\{([a-zA-Z0-9_]+)\}/g;

export function registrationText(
  locale: Locale,
  key: RegistrationCopyKey,
  values: Record<string, string | number> = {},
): string {
  return copy[locale][key].replace(placeholderPattern, (placeholder, name: string) => (
    name in values ? String(values[name]) : placeholder
  ));
}
