import type { Locale } from "@/i18n/messages";

const copy = {
  title: ["复核批改", "Grading Review"],
  average: ["平均得分率", "Average score"],
  lowConfidence: ["低置信题次", "Low-confidence responses"],
  disagreement: ["专家分歧大", "High model disagreement"],
  annotated: ["已复核", "Reviewed"],
  startReview: ["开始优先复核", "Start priority review"],
  viewResult: ["查看任一结果", "View a result"],
  searchPlaceholder: ["例如：90 分以下的学生、专家分歧、Q2，或从高到低…", "For example: students below 90, model disagreement, Q2, or high to low…"],
  searchLabel: ["智能筛选批改结果", "Smart-filter grading results"],
  applyFilter: ["应用筛选", "Apply filter"],
  interpreting: ["理解中…", "Interpreting…"],
  filterPrivacyHint: ["本地预设优先；未识别时模型只解析这句指令，不接收学生成绩。", "Local presets run first; on fallback, the model sees only this instruction, not student scores."],
  localRecognized: ["本地规则已识别 · 未调用模型", "Matched locally · no model call"],
  modelInterpreted: ["模型仅解析指令", "Model interpreted instruction only"],
  dismiss: ["关闭提示", "Dismiss"],
  modelSettings: ["查看模型配置", "View model settings"],
  heatmap: ["学生 × 题目复核热力图", "Student × question review heatmap"],
  queue: ["复核队列", "Review queue"],
  review: ["复核", "Review"],
  low: ["低", "Low"],
  ok: ["OK", "OK"],
  commented: ["批注", "Note"],
  edited: ["已修改", "Edited"],
  confirmed: ["已确认", "Confirmed"],
  hard: ["无有效分数", "No valid score"],
  aiDefault: ["沿用 AI 分", "AI score retained"],
  noQueue: ["当前没有低置信、专家分歧或后端复核标记。", "No low-confidence, disagreement, or backend review flags were found."],
  noMatch: ["没有符合当前筛选条件的题次。清空输入可恢复全部结果。", "No responses match this filter. Clear it to restore all results."],
  clear: ["清空筛选", "Clear filter"],
  loadError: ["暂时无法读取批改结果", "Grading results could not be loaded"],
  loadErrorDescription: ["任务数据没有被修改。请刷新后重试，或从历史任务重新进入。", "Task data was not changed. Refresh or reopen it from History."],
  retry: ["重新读取", "Retry"],
  missingTask: ["缺少任务信息，请从工作台或历史任务重新进入。", "Task information is missing. Reopen it from Workspace or History."],
  loading: ["正在读取批改结果…", "Loading grading results…"],
  empty: ["当前任务没有可显示的批改结果。", "This task has no grading results to display."],
  viewHistory: ["查看历史任务", "View History"],
  lowReason: ["作答低置信", "Low-confidence response"],
  disagreementReason: ["专家分歧", "Model disagreement"],
  anomalyReason: ["分数异常", "Score anomaly"],
  reviewReason: ["建议复核", "Review suggested"],
  savedPendingReason: ["修改已保存", "Changes saved"],
  filtered: ["筛选后 {students} 位学生 · {questions} 道题 · {cells} 个题次", "Filtered to {students} students · {questions} questions · {cells} responses"],
  studentId: ["学号", "Student ID"],
  studentName: ["姓名", "Name"],
  action: ["操作", "Action"],
  view: ["查看", "View"],
  viewDetails: ["查看批改详情", "View grading details"],
  continueReview: ["继续复核（还剩 {count} 题）", "Continue review ({count} left)"],
  confirmReview: ["确认正式结果", "Confirm final results"],
  confirming: ["正在确认…", "Confirming…"],
  confirmDisabled: ["请先补全无分结果。", "Add missing scores first."],
  viewFinalResults: ["查看最终结果", "View final results"],
  remainingHint: ["还有 {count} 个题次无有效分数，补全后才能生成正式结果。", "{count} responses have no valid score; add scores before finalizing."],
  lockedResultsRemaining: ["还有 {count} 个题次无有效分数，暂不能查看结果分析。", "{count} responses have no valid score; Results & Analysis remains locked."],
  lockedResultsReady: ["有效 AI 分会直接用于正式结果；请先确认。", "Valid AI scores go directly to final results; confirm first."],
  readyHint: ["有效 AI 分会直接用于正式结果；可按需复核。", "Valid AI scores go directly to final results; review as needed."],
  historyHint: ["当前为已完成任务的只读复核记录，可查看批改详情或进入最终结果。", "This is a read-only review record. Open grading details or final results."],
} as const;

export type ReviewOverviewCopyKey = keyof typeof copy;

export function reviewOverviewText(locale: Locale, key: ReviewOverviewCopyKey): string {
  return copy[key][locale === "en-US" ? 1 : 0];
}
