import type { SourcePreviewMockScenario } from "@/lib/sourcePreview";

export async function loadSourcePreviewMock(scenario: SourcePreviewMockScenario, attempt: number): Promise<Blob> {
  if (scenario.descriptor.status !== "available") {
    throw new Error("source_preview_unavailable");
  }

  await new Promise((resolve) => window.setTimeout(resolve, 180));
  if (scenario.variant === "error" && attempt === 0) {
    throw new Error("source_preview_mock_read_failed");
  }

  return scenario.descriptor.preview_kind === "pdf"
    ? createMockPdf(scenario.descriptor.display_name)
    : createMockImage(scenario.descriptor.display_name);
}

function createMockPdf(displayName: string): Blob {
  const label = escapePdfText(displayName);
  const stream = [
    "0.96 g 46 56 520 680 re f",
    "0.145 0.388 0.922 rg 46 682 520 54 re f",
    "BT /F1 18 Tf 1 1 1 rg 68 713 Td (SmarTAI Original File Preview) Tj ET",
    `BT /F1 10 Tf 0.25 g 68 658 Td (${label}) Tj ET`,
    "0.86 G 0.7 w 68 626 m 540 626 l S",
    "BT /F1 12 Tf 0.15 g 68 598 Td (1. Review the source document beside recognized content.) Tj ET",
    "BT /F1 12 Tf 0.15 g 68 566 Td (2. Correct recognition without leaving the review page.) Tj ET",
    "0.88 G 0.6 w 68 526 m 540 526 l S 68 492 m 540 492 l S 68 458 m 540 458 l S",
    "68 424 m 540 424 l S 68 390 m 540 390 l S 68 356 m 540 356 l S",
    "68 322 m 540 322 l S 68 288 m 540 288 l S 68 254 m 540 254 l S",
    "BT /F1 10 Tf 0.42 g 68 94 Td (Development mock - no server path or public file URL.) Tj ET",
  ].join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${asciiLength(stream)} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((object, index) => {
    offsets.push(asciiLength(pdf));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = asciiLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return new Blob([pdf], { type: "application/pdf" });
}

function createMockImage(displayName: string): Blob {
  const label = escapeXml(displayName);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1200" viewBox="0 0 900 1200">
  <rect width="900" height="1200" fill="#ffffff"/>
  <rect x="0" y="0" width="900" height="112" fill="#2563eb"/>
  <text x="64" y="70" fill="#ffffff" font-family="Inter,Arial,sans-serif" font-size="30" font-weight="700">SmarTAI Original File Preview</text>
  <text x="64" y="158" fill="#64748b" font-family="Inter,Arial,sans-serif" font-size="18">${label}</text>
  <rect x="64" y="210" width="772" height="150" rx="10" fill="#f1f5f9" stroke="#d9e0e9"/>
  <text x="94" y="264" fill="#111827" font-family="Inter,Arial,sans-serif" font-size="23" font-weight="700">Whole-file comparison mock</text>
  <text x="94" y="306" fill="#475569" font-family="Inter,Arial,sans-serif" font-size="18">Use the recognized content beside this page to verify every answer.</text>
  <g stroke="#cbd5e1" stroke-width="2">${Array.from({ length: 16 }, (_, index) => `<line x1="70" y1="${420 + index * 42}" x2="830" y2="${420 + index * 42}"/>`).join("")}</g>
  <text x="64" y="1150" fill="#64748b" font-family="Inter,Arial,sans-serif" font-size="16">Development mock · no server path or public URL</text>
</svg>`;
  // This fixed, script-free SVG is generated by our code only. User-provided SVG remains unsupported.
  return new Blob([svg], { type: "image/svg+xml" });
}

function escapePdfText(value: string): string {
  return value
    .replace(/[^\x20-\x7e]/g, "?")
    .replace(/[\\()]/g, (character) => `\\${character}`);
}

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function asciiLength(value: string): number {
  return new TextEncoder().encode(value).length;
}
