version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_PORT=8000
      - FRONTEND_URLS=http://localhost:8501,https://smartai-2025-smartai-frontendapp-iie6tb.streamlit.app
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend