services:
  - type: web
    name: smartai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: FRONTEND_URLS
        value: https://smartai-2025-smartai-frontendapp-iie6tb.streamlit.app,http://localhost:8501