[server]
port = 8501
address = "localhost"
headless = false

[client]
showSidebarNavigation = false

[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"