import { chromium, firefox, webkit } from '@playwright/test';
import { expect } from '@playwright/test';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const qaApp = process.env.DRAFT_QA_APP_URL || 'http://127.0.0.1:53971';
const qaApi = process.env.DRAFT_QA_API_URL || 'http://127.0.0.1:8037';
for (const url of [qaApp, qaApi]) if (!['127.0.0.1', 'localhost', '[::1]'].includes(new URL(url).hostname)) throw new Error('Draft QA requires isolated loopback services.');
const qaOut = process.env.DRAFT_QA_OUTPUT || path.join(os.tmpdir(), 'smartai-explicit-draft-evidence');
await fs.mkdir(qaOut, { recursive: true });
const origin=qaApp,out=qaOut,results=[];
const expert={provider_id:'qa-local-model',provider_type:'openai',model:'qa-local',enabled:true,scope:'owner',is_shared:false,editable:true,is_default:true,max_concurrent:1,rpm:0};
const setup={schema_version:1,selected_provider_ids:[expert.provider_id],primary_provider_id:expert.provider_id,aggregation_method:'single',multi_sample_n:1,knowledge_scope:'none',strictness:0,allow_partial_credit:true,feedback_tone:'neutral',feedback_length:'medium',feedback_language:'zh',suggest_corrections:false,low_confidence_threshold:.75,teacher_notes:''};
function task(id,status){return {task_id:id,name:'隔离草稿业务页面',owner_id:'qa-teacher',status,workflow_revision:7,course_id:null,created_at:1,updated_at:1,problem_count:2,student_count:1,kb_docs:{},kb_doc_count:0,grading_setup_configured:true,problem_data:{Q1:{q_id:'Q1',number:'1',type:'Proof',stem:'证明题样本',max_score:10,criterion:'原评分标准',reference_answer:'原参考答案',preparation_issues:[],review_status:'confirmed'},Q2:{q_id:'Q2',number:'2',type:'Programming',stem:'计算平方的 Python 程序',max_score:10,criterion:'程序正确',reference_answer:'使用 n*n',solution_code:'def square(n): return n*n',test_cases:[{input:'2',expected_output:'4',description:'样例',visibility:'example',source:'teacher',sandbox_feasible:true}],preparation_issues:[],review_status:'confirmed'}},student_data:{S001:{stu_id:'S001',stu_name:'测试学生',source_filename:'isolated-answer.txt',identity_status:'matched',identity_match_method:'filename',stu_ans:[{q_id:'Q1',number:'1',type:'Proof',content:'原作答',review_status:'pending',flag:[]},{q_id:'Q2',number:'2',type:'Programming',content:'return 4',review_status:'pending',flag:[]}]}},results:[{student_id:'S001',student_name:'测试学生',corrections:['Q1','Q2'].map(q_id=>({q_id,type:q_id==='Q1'?'Proof':'Programming',score:7,max_score:10,confidence:.6,comment:'原模型评语',steps:[],expert_results:[],requires_human_review:true,review_reasons:['low_confidence'],review_status:'pending',teacher_comment:''}))}]}}
async function snapshot(page){await page.getByRole('button',{name:'暂存',exact:true}).last().click();await expect(page.getByText(/已暂存 ·/).last()).toBeVisible();}
async function restore(page,assert){await snapshot(page);await page.reload();await assert();}
for(const [engineName,engine] of Object.entries({chromium,firefox,webkit})){
 const browser=await engine.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>{localStorage.setItem('smartai_token','demo-teacher-pages');localStorage.setItem('smartai_locale','zh-CN');});
 const page=await context.newPage();page.setDefaultTimeout(8000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('BROWSER ERROR',m.text());});let calls=[];let currentTask;let scenario;let referenceExpired=false;
 await context.route('**/experts/stage-options',r=>r.fulfill({json:[expert]}));await context.route('**/experts/available',r=>r.fulfill({json:[expert]}));
 await context.route(/\/tasks\/draft-fixture-[^/]+(?:\/|$)/,async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname; if(url.origin !== qaApi)return r.continue(); if(req.method()!=='GET'){calls.push({method:req.method(),path});if(scenario==='material-preflight' && path.endsWith('/material-imports/preflight'))return r.fulfill({json:{source_token:'qa-prepared-material',task_id:currentTask.task_id,status:'ready',provider_call_performed:false}});return r.fulfill({status:503,json:{detail:'QA deliberately fails formal submit; no real provider'}})}
  if(path.endsWith('/material-imports/draft-reference'))return r.fulfill(referenceExpired?{status:410,json:{detail:'expired'}}:{json:{valid:true,task_id:currentTask.task_id}});
  if(path.endsWith('/source-files'))return r.fulfill({json:{task_id:currentTask.task_id,workflow_revision:7,problem_sources:[],submission_sources:{}}});
  if(path.endsWith('/grading-setup'))return r.fulfill({json:{task_id:currentTask.task_id,task_status:currentTask.status,workflow_revision:7,configured:true,grading_setup:setup,suggested_setup:setup,available_experts:[expert],knowledge:{scope_options:['none','all_task_docs'],task_doc_count:0,task_docs:[]},readiness:{ready:true,blocking_issues:[],warnings:[]}}});
  if(path.endsWith('/result'))return r.fulfill({json:{task_id:currentTask.task_id,status:currentTask.status,results:currentTask.results,workflow_revision:7}});
  if(path.endsWith('/ai-completions/preflight'))return r.fulfill({json:{status:'ready',task_id:currentTask.task_id,overwrite_policy:'missing_only',missing_targets:[{target_id:'Q2:test_cases',q_id:'Q2',question_number:'2',question_type:'Programming',target:'test_cases',label:'测试用例'}],summary:{question_count:2,missing_count:1,by_target:{criterion:0,reference_answer:0,solution_code:0,test_cases:1}},workflow_revision:7,provider_call_performed:false,storage:'local-QA'}});
  if(path.endsWith('/material-imports/plan-qa'))return r.fulfill({json:{job_id:'plan-qa',task_id:currentTask.task_id,status:'ready',request_fingerprint:'qa-plan',source:{kind:'upload',filename:'qa-rubric.txt'},targets:['criterion'],structure_mode:'organized',extraction_hint:'',overwrite_policy:'missing_only',candidates:[{candidate_id:'candidate-1',q_id:'Q1',target:'criterion',match_status:'exact',text_value:'待核对评分标准',confidence:.9,source_excerpt:'样本',source_location:'第1段',reason:'题号匹配',would_overwrite:false}],summary:{},applied_candidate_ids:[],workflow_revision:7,created_at:1,expires_at:Date.now()/1000+3600,storage:'local-QA'}});
  if(path.includes('/problem-sources/library'))return r.fulfill({json:{scope:'course',items:[]}});
  if(path.endsWith('/kb') || path.endsWith('/kb/docs') || path.endsWith('/kb_docs'))return r.fulfill({json:{docs:[]}});
  if(path===`/tasks/${currentTask.task_id}`)return r.fulfill({json:currentTask});
  return r.fulfill({json:{items:[],version:7,results:currentTask.results}});
 });
 const cases=[
 ['questions','problems_ready','questions/Q1/content',async()=>{await page.getByRole('button',{name:'修改第 1 题满分与评分标准'}).click();await page.getByLabel('第 1 题满分',{exact:true}).fill('15');await page.getByLabel('第 1 题评分标准').fill('显式评分标准');await page.getByRole('button',{name:'题目 · 修改',exact:true}).first().click();await page.locator('textarea').filter({hasNot:page.locator('[aria-label]')}).first().fill('暂存题干');await restore(page,async()=>{await expect(page.getByLabel('第 1 题满分',{exact:true})).toHaveValue('15');await expect(page.getByLabel('第 1 题评分标准')).toHaveValue('显式评分标准');await expect(page.locator('textarea').filter({hasNot:page.locator('[aria-label]')}).first()).toHaveValue('暂存题干')});await page.screenshot({path:`${out}/${engineName}-long-question.png`,fullPage:true});}],
 ['programming','problems_ready','questions/Q2/content',async()=>{await page.getByRole('button',{name:'参考代码 · 修改',exact:true}).click();const code=page.locator('textarea').first();await code.fill('def square(n):\n    return n ** 2');const panel=page.locator('section').filter({has:page.getByRole('heading',{name:'测试样例',exact:true})}).last();await panel.getByRole('button',{name:'修改',exact:true}).click();await page.getByLabel('输入',{exact:true}).fill('3');await page.getByLabel('期望输出',{exact:true}).fill('9');await panel.getByRole('combobox').selectOption('hidden');await restore(page,async()=>{await expect(code).toHaveValue('def square(n):\n    return n ** 2');await expect(page.getByLabel('输入',{exact:true})).toHaveValue('3');await expect(page.getByLabel('期望输出',{exact:true})).toHaveValue('9');await expect(panel.getByRole('combobox')).toHaveValue('hidden')});}],
 ['material-preflight','problems_ready','questions/import',async()=>{referenceExpired=false;await page.getByRole('button',{name:/上传新文件/}).first().click();await page.locator('input[type=file]').setInputFiles({name:'cached-material.txt',mimeType:'text/plain',buffer:Buffer.from('cached file bytes')});const start=page.getByRole('button',{name:'开始导入并匹配到题目',exact:true});await start.click();await expect.poll(()=>calls.filter(x=>x.path.endsWith('/material-imports')).length).toBe(1);await expect(start).toBeEnabled();await restore(page,async()=>expect(page.getByText(/已选择：cached-material.txt/)).toBeVisible());expect(calls.filter(x=>x.path.endsWith('/preflight')).length).toBe(1);expect(calls.filter(x=>x.path.endsWith('/material-imports')).length).toBe(1);await expect(start).toBeEnabled();await start.click();await expect.poll(()=>calls.filter(x=>x.path.endsWith('/material-imports')).length).toBe(2);expect(calls.filter(x=>x.path.endsWith('/preflight')).length).toBe(1);await expect(start).toBeEnabled();await snapshot(page);referenceExpired=true;await page.reload();await expect(page.getByText(/已上传的资料引用已过期/)).toBeVisible();await expect(page.getByText(/已选择：cached-material.txt/)).toBeVisible();await snapshot(page);}],
 ['answers','submissions_ready','students/S001',async()=>{await page.getByRole('button',{name:'修改',exact:true}).first().click();await page.locator('textarea').first().fill('显式学生作答');await page.getByRole('button',{name:/修正身份/}).click();await page.getByLabel('姓名',{exact:true}).fill('草稿姓名');await restore(page,async()=>{await expect(page.getByLabel('姓名',{exact:true})).toHaveValue('草稿姓名');await expect(page.locator('textarea').first()).toHaveValue('显式学生作答')});}],
 ['review','graded','review/S001/all',async()=>{const score=page.getByLabel(/第 1 题 最终得分|1 最终得分/).first();await score.fill('8');const comment=page.locator('textarea').first();await comment.fill('暂存评语');await restore(page,async()=>{await expect(score).toHaveValue('8');await expect(comment).toHaveValue('暂存评语')});}],
 ['grading','submissions_ready','grading-setup',async()=>{await page.getByRole('button',{name:'展开高级设置'}).click();const notes=page.getByLabel('批改注意事项',{exact:false});await notes.fill('草稿教师指令');await restore(page,async()=>expect(notes).toHaveValue('草稿教师指令'));}],
 ['material','problems_ready','questions/import',async()=>{await page.getByRole('button',{name:/上传新文件/}).first().click();await page.locator('input[type=file]').setInputFiles({name:'material.txt',mimeType:'text/plain',buffer:Buffer.from('local material bytes')});await restore(page,async()=>expect(page.getByText(/已选择：material.txt/)).toBeVisible());}],
 ['material-plan','problems_ready','questions/import/review/plan-qa',async()=>{const box=page.getByRole('checkbox').first();await box.uncheck();await restore(page,async()=>expect(box).not.toBeChecked());}],
 ['ai','problems_ready','questions/ai-complete',async()=>{const count=page.getByRole('combobox').first();await count.selectOption('10');await restore(page,async()=>expect(count).toHaveValue('10'));}],
 ['submissions','problems_ready','submissions/upload',async()=>{await page.locator('input[type=file]').first().setInputFiles({name:'S001.txt',mimeType:'text/plain',buffer:Buffer.from('student bytes')});await restore(page,async()=>expect(page.getByText('S001.txt',{exact:true}).first()).toBeVisible());}],
 ['charts','graded','results/visualizations',async()=>{const input=page.locator('form[role=search] input').last();await input.fill('草稿图表需求');await restore(page,async()=>expect(input).toHaveValue('草稿图表需求'));}]
 ];
 for(const [name,status,path,run] of cases){scenario=name;currentTask=task(`draft-fixture-${engineName}-${name}`,status);calls=[];
  try{await page.goto(`${origin}/tasks/${currentTask.task_id}/${path}`);await run();if(name!=='material-preflight')expect(calls).toEqual([]);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${out}/${engineName}-${name}-mobile.png`,fullPage:true});await page.setViewportSize({width:1440,height:1000});results.push({engine:engineName,page:name,passed:true,mutations:calls.length});console.log(engineName,name,'passed');}
  catch(e){await page.screenshot({path:`${out}/${engineName}-${name}-failure.png`,fullPage:true});console.log(engineName,name,'FAILED',String(e));console.log((await page.locator('body').innerText()).slice(0,1800));results.push({engine:engineName,page:name,failure:String(e),mutations:calls});}
 }
 await browser.close();results.push({engine:engineName,errors});
}
await fs.writeFile(`${out}/explicit-page-results.json`,JSON.stringify(results,null,2));if(results.some(x=>x.failure||x.errors?.length))process.exitCode=1;
